### ISSUE TITLE
Basic EECS 280 Materials

### ISSUE THREAD

**Issue by ghost** [UMich-EECS-resources/wiki#5]
I'm not sure how basic we want to go with this, but would it be helpful to add a few of the Quick References from EECS 280?  Specifically I was thinking the CAEN_Linux and Compiling references.

**Comment by amodell** [comment]
I know we already have a page for a CAEN quickstart, the caen_linux resource may go well there?  (I don't quite know the document as I took 280 many years ago).

Right now, we have a lot of stuff on Makefiles, but not so much on compiling in general, so if you want to start a page for that, I'd say go ahead!
